name: Build & Deploy
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        with:
          host: ${{secrets.SSH_HOST}} 
          key: ${{secrets.SSH_KEY}} 
          username: ${{ secrets.SSH_USERNAME }} 
     
          script: |
            mkdir test 
            cd test 
            git clone https://github.com/nemofalcon/ci-cd.git
            echo 'Deployment successful to digital ocean' 


          
